Repository Metis-Team/mts_enhanced, pull requests merged in 2020-04, with the labels that each got.

#34 Port from Achilles to ZEN
  addons/zeus/config.cpp
  addons/zeus/functions/fnc_artyFireMissionHE.sqf
  addons/zeus/functions/fnc_artyFireMissionILLUM.sqf
  addons/zeus/functions/fnc_artyFireMissionSMOKE.sqf
  addons/zeus/functions/fnc_moduleArtillery.sqf
  addons/zeus/functions/fnc_moduleForgetTarget.sqf
  addons/zeus/functions/fnc_moduleRevealTarget.sqf
  addons/zeus/functions/fnc_moduleTargetKnowledge.sqf
  addons/zeus/functions/fnc_moduleUnflipVehicle.sqf
  addons/zeus/functions/fnc_setAIBehaviour.sqf
  addons/zeus/functions/fnc_setAICombatMode.sqf
  addons/zeus/functions/fnc_switchAIPathBehaviour.sqf
Labels: enhancement

#33 General cleanup fixes
  addons/common/XEH_preInit.sqf
  addons/common/functions/fnc_addGrassCutter.sqf
  addons/cords/XEH_preInit.sqf
  addons/cup_enhancement/$PBOPREFIX$
  addons/cup_enhancement/CfgWorlds.hpp
  addons/cup_enhancement/config.cpp
  addons/cup_enhancement/script_component.hpp
  addons/drill/XEH_preInit.sqf
  addons/zeus/XEH_PREP.hpp
  addons/zeus/XEH_postInit.sqf
  addons/zeus/XEH_preInit.sqf
  addons/zeus/functions/fnc_moduleShowProjectiles.sqf
  addons/zeus/stringtable.xml
Labels: bug fix, cleanup

#32 Rename flagmarker to items
  addons/flagmarker/$PBOPREFIX$
  addons/flagmarker/CfgWeapons.hpp
  addons/flagmarker/XEH_PREP.hpp
  addons/flagmarker/functions/fnc_addACEActions.sqf
  addons/flagmarker/functions/fnc_pickupFlag.sqf
  addons/flagmarker/functions/fnc_placeFlag.sqf
  addons/flagmarker/functions/script_component.hpp
  addons/flagmarker/stringtable.xml
  addons/items/$PBOPREFIX$
  addons/items/CfgEventHandlers.hpp
  addons/items/CfgVehicles.hpp
  addons/items/CfgWeapons.hpp
  addons/items/XEH_PREP.hpp
  addons/items/XEH_missionDisplayLoad.sqf
  addons/items/XEH_postInit.sqf
  addons/items/XEH_preInit.sqf
  addons/items/XEH_preStart.sqf
  addons/items/config.cpp
  addons/items/data/Flag_yellow_co.paa
  addons/items/data/ui/flags/mts_flag_blue_carry_icon.paa
  addons/items/data/ui/flags/mts_flag_blue_item_icon.paa
  addons/items/data/ui/flags/mts_flag_blue_place_icon.paa
  addons/items/data/ui/flags/mts_flag_furl_icon.paa
  addons/items/data/ui/flags/mts_flag_green_carry_icon.paa
  addons/items/data/ui/flags/mts_flag_green_item_icon.paa
  addons/items/data/ui/flags/mts_flag_green_place_icon.paa
  addons/items/data/ui/flags/mts_flag_pickup_icon.paa
  addons/items/data/ui/flags/mts_flag_red_carry_icon.paa
  addons/items/data/ui/flags/mts_flag_red_item_icon.paa
  addons/items/data/ui/flags/mts_flag_red_place_icon.paa
  addons/items/data/ui/flags/mts_flag_white_icon.paa
  addons/items/data/ui/flags/mts_flag_yellow_carry_icon.paa
  addons/items/data/ui/flags/mts_flag_yellow_item_icon.paa
  addons/items/data/ui/flags/mts_flag_yellow_place_icon.paa
  addons/items/data/ui/markers/mts_marker_mines_item_icon.paa
  addons/items/data/ui/markers/mts_marker_mines_place_icon.paa
  addons/items/data/ui/markers/mts_marker_pickup_icon.paa
  addons/items/data/ui/markers/mts_marker_white_icon.paa
  addons/items/data/ui/markers/mts_marker_yellow_item_icon.paa
  addons/items/data/ui/markers/mts_marker_yellow_place_icon.paa
  addons/items/functions/fnc_addFlagACEActions.sqf
  addons/items/functions/fnc_addMarkerACEActions.sqf
  addons/items/functions/fnc_carryFlag.sqf
  addons/items/functions/fnc_handleScrollWheel.sqf
  addons/items/functions/fnc_pickupItem.sqf
  addons/items/functions/fnc_placeItem.sqf
  addons/items/functions/script_component.hpp
  addons/items/script_component.hpp
  addons/items/stringtable.xml
Labels: enhancement

#37 Fix selection error when player respawned manually
  addons/zeus/functions/fnc_drawACEUnconsciousIcon.sqf
Labels: bug fix

#38 Disable debugging
  addons/items/script_component.hpp
Labels: bug fix
