Repository Metis-Team/mts_enhanced, pull requests merged in 2023-09, with the labels that each got.

#101 Armory - Minor fixes and some little features
  addons/armory/CfgEventHandlers.hpp
  addons/armory/XEH_PREP.hpp
  addons/armory/XEH_postInit.sqf
  addons/armory/XEH_preInit.sqf
  addons/armory/defines.hpp
  addons/armory/functions/fnc_buttonCreateEquipment.sqf
  addons/armory/functions/fnc_createEquipment.sqf
  addons/armory/functions/fnc_equipBackpack.sqf
  addons/armory/functions/fnc_equipLoadout.sqf
  addons/armory/functions/fnc_initEquipment.sqf
  addons/armory/functions/fnc_openNewEquipmentDialog.sqf
  addons/armory/functions/fnc_saveEquipment.sqf
  addons/armory/functions/fnc_setEditArea.sqf
  addons/armory/functions/fnc_updateArsenal.sqf
  addons/armory/functions/fnc_updateBackpack.sqf
  addons/armory/functions/fnc_updateEditors.sqf
  addons/armory/functions/fnc_updateLoadout.sqf
  addons/armory/initSettings.hpp
  addons/armory/script_component.hpp
  addons/armory/stringtable.xml
  addons/armory/ui/RscAttributes.hpp
Labels: enhancement, bug fix, optimization

#102 Add VSCode workspace settings
  .gitignore
  .vscode/extensions.json
  .vscode/settings.json
  .vscode/sqf.code-snippets
  .vscode/tasks.json
Labels: ignore changelog, tools

#103 Armory - Fix player DB connection check and move initialization of module
  addons/armory/XEH_postInit.sqf
  addons/armory/XEH_preInit.sqf
  addons/armory/functions/fnc_createEquipment.sqf
  addons/armory/functions/fnc_initEquipment.sqf
  addons/armory/functions/fnc_updateArsenal.sqf
  addons/armory/functions/fnc_updateBackpack.sqf
  addons/armory/functions/fnc_updateEditors.sqf
  addons/armory/functions/fnc_updateLoadout.sqf
Labels: bug fix
